dwp/queue-triage

.buckconfig
As per Issue #14 - this change enables dependencies to be downloaded automatically from the defined maven repo.
=> #14: Automatically attempt to d/l dependencies from maven when building

.travis.yml
Changed the travis/slack integration to only publish builds on the main repo (i.e. ignore forks).
=> Secure the Slack/Travis integration

core/client/src/main/java/uk/gov/dwp/queue/triage/core/client/resend/ResendFailedMessageClient.java, core/component-test/src/main/java/uk/gov/dwp/queue/triage/core/configuration/CoreClientConfiguration.java, core/component-test/src/main/java/uk/gov/dwp/queue/triage/core/resend/ResendFailedMessageWhenStage.java, core/component-test/src/test/java/uk/gov/dwp/queue/triage/core/resend/ResendFailedMessageComponentTest.java, core/dao-mongo/src/main/java/uk/gov/dwp/queue/triage/core/dao/mongo/FailedMessageConverter.java, core/dao-mongo/src/test/java/uk/gov/dwp/queue/triage/core/dao/mongo/FailedMessageConverterTest.java, core/search/BUCK, core/search/src/main/java/uk/gov/dwp/queue/triage/core/search/FailedMessageSearchService.java, core/search/src/main/java/uk/gov/dwp/queue/triage/core/search/SearchFailedMessageResponseAdapter.java, core/search/src/main/java/uk/gov/dwp/queue/triage/core/search/mongo/MongoFailedMessageSearchService.java, core/search/src/main/java/uk/gov/dwp/queue/triage/core/search/mongo/spring/MongoSearchConfiguration.java, core/search/src/test/java/uk/gov/dwp/queue/triage/core/search/mongo/MongoFailedMessageSearchServiceTest.java, core/server/BUCK, core/server/src/main/java/uk/gov/dwp/queue/triage/core/QueueTriageCoreApplication.java, core/server/src/main/java/uk/gov/dwp/queue/triage/core/configuration/FailedMessageResourceConfiguration.java, core/server/src/main/java/uk/gov/dwp/queue/triage/core/resource/resend/ResendFailedMessageResource.java, core/server/src/main/java/uk/gov/dwp/queue/triage/core/resource/search/FailedMessageSearchResource.java, core/server/src/test/java/uk/gov/dwp/queue/triage/core/resource/resend/ResendFailedMessageResourceTest.java, core/server/src/test/java/uk/gov/dwp/queue/triage/core/resource/search/FailedMessageSearchResourceTest.java
As per the commit messages:
- Refactored the `FailedMessageSearchService` to return `FailedMessage` (this used to return `SearchFailedMessageResponse` - which is part of the client-side API), as a future enhancement we could pass in an adapter to search function and return different objects.
- Messages can now be marked for Resending via a REST endpoint (next step is to add the ability to actually resend).
=> Issue 23 resend failed message

core/dao-mongo-test-support/src/main/resources/mongo-dao-test.properties, core/dao-mongo/BUCK, core/dao-mongo/src/main/java/uk/gov/dwp/queue/triage/core/dao/mongo/configuration/MongoDaoConfig.java, core/dao-mongo/src/main/java/uk/gov/dwp/queue/triage/core/dao/mongo/configuration/MongoDaoProperties.java, core/dao-mongo/src/main/resources/mongo-queue-triage-roles.sh, core/dao-mongo/src/main/resources/mongo-queue-triage-users.sh, core/dao-mongo/src/test/java/uk/gov/dwp/queue/triage/core/dao/mongo/configuration/MongoDaoPropertiesTest.java, core/dao-mongo/src/test/resources/mongo-dao-defaults.yml, core/dao-mongo/src/test/resources/mongo-dao-multiple-servers-and-auth.yml, core/dao/BUCK, core/message-classification/src/main/java/uk/gov/dwp/queue/triage/core/classification/server/executor/MessageClassificationExecutorService.java, core/resend/BUCK, core/resend/src/main/java/uk/gov/dwp/queue/triage/core/resend/ResendScheduledExecutorService.java, core/resend/src/main/java/uk/gov/dwp/queue/triage/core/resend/ResendScheduledExecutorsResource.java, core/resend/src/main/java/uk/gov/dwp/queue/triage/core/resend/spring/FailedMessageSenderBeanDefinitionFactory.java, core/resend/src/main/java/uk/gov/dwp/queue/triage/core/resend/spring/ResendBeanDefinitionFactory.java, core/resend/src/main/java/uk/gov/dwp/queue/triage/core/resend/spring/configuration/ResendFailedMessageConfiguration.java, core/resend/src/test/java/uk/gov/dwp/queue/triage/core/resend/spring/ResendBeanDefinitionFactoryTest.java, core/server/src/main/resources/application.yml, project
1. Remove the post processing of the ResendScheduledExecutorResource which was causing some Beans not to be instantiated properly.
2. Added support for multiple servers and (optional) authentication
```yaml
dao:
mongo:
serverAddresses:
- host: localhost
port: 27017
failedMessage:
name: failedMessage
username: failedMessageUser
password: Passw0rd
```
3. Wait for jobs to complete when executing requests via the REST endpoints (only currently used by tests)
=> Improve mongo connection options

core/component-test/BUCK, lib/test/BUCK, web/component-test/BUCK
Generate JGiven HTML output which could then be published to S3, GitHub wiki/pages.
Currently output is published to
* `buck-out/gen/core/component-test/generate-jgiven-html-reports/jgiven-html-reports`
* `buck-out/gen/web/component-test/generate-jgiven-html-reports/jgiven-html-reports`
Resolves #64
=> Generate JGiven HTML output

core/message-classification/BUCK, core/message-classification/src/main/java/uk/gov/dwp/queue/triage/core/classification/server/configuration/MessageClassificationConfiguration.java, core/message-classification/src/main/java/uk/gov/dwp/queue/triage/core/classification/server/configuration/MessageClassificationProperties.java, core/message-classification/src/test/java/uk/gov/dwp/queue/triage/core/classification/server/configuration/MessageClassificationPropertiesTest.java, core/server/src/main/resources/application.yml, lib/spring/BUCK
Message classification job is now configurable from `application.yml`
```
messageClassification:
initialDelay: 0
frequency: 60
timeUnit: SECONDS
```
Resolves #56
=> Issue 56 - Configurable Message Classification executor

common/cxf/BUCK, core/client-test-support/src/main/java/uk/gov/dwp/queue/triage/core/client/StatusHistoryResponseMatcher.java, core/client/BUCK, core/client/src/main/java/uk/gov/dwp/queue/triage/core/client/status/FailedMessageStatusHistoryClient.java, core/client/src/main/java/uk/gov/dwp/queue/triage/core/client/status/StatusHistoryResponse.java, core/component-test/src/main/java/uk/gov/dwp/queue/triage/core/status/StatusHistoryStage.java, core/component-test/src/test/java/uk/gov/dwp/queue/triage/core/search/SearchFailedMessageComponentTest.java, core/component-test/src/test/java/uk/gov/dwp/queue/triage/core/status/FailedMessageStatusHistoryComponentTest.java, core/domain/src/main/java/uk/gov/dwp/queue/triage/core/domain/StatusHistoryEvent.java, core/sample-data/BUCK, core/sample-data/src/main/java/uk/gov/dwp/queue/triage/sample/data/create/CreateFailedMessages.java, core/server/src/main/java/uk/gov/dwp/queue/triage/core/configuration/FailedMessageResourceConfiguration.java, core/server/src/main/java/uk/gov/dwp/queue/triage/core/resource/status/FailedMessageStatusHistoryResource.java, core/server/src/test/java/uk/gov/dwp/queue/triage/core/resource/search/FailedMessageResponseFactoryTest.java, core/server/src/test/java/uk/gov/dwp/queue/triage/core/resource/status/FailedMessageStatusHistoryResourceTest.java, lib/apache-cxf/BUCK
- Introduced an endpoint to get Status History for a Failed Message (see `FailedMessageStatusHistoryClient` for details of the API)
- Added a class `CreateFailedMessages` (in the `queue-triage-sample-data` module) to generate test data via the REST API
=> Introduce endpoint to get Status History for a FailedMessage

.travis.yml, README.md, core/component-test/BUCK, lib/httpcomponents/BUCK, lib/selenide/BUCK, lib/selenium/BUCK, lib/selenium/firefox-driver/BUCK, web/component-test/BUCK, web/component-test/src/main/java/uk/gov/dwp/queue/triage/web/component/labels/LabelManagementWhenStage.java, web/component-test/src/main/java/uk/gov/dwp/queue/triage/web/component/search/SearchFailedMessageWhenStage.java, web/component-test/src/main/java/uk/gov/dwp/queue/triage/web/component/w2ui/FailedMessageGrid.java
- Change the way in which certain elements on the w2ui grid are selected,
- Component tests now run separately from the rest of the "Unit Tests", the `mongo-dao` module and the `core-component-test` module tests would often overlap, leading to unpredictable behaviour.
- Firefox is run in a Docker container (this enables more predicitable/repeatable behaviour locally and on travis).
Resolves #102
=> Issue 102 - Improve test stability

core/server/src/main/resources/logback.xml, lib/spring/BUCK, web/server/src/main/resources/application.yml, web/server/src/main/resources/logback.xml, web/spring-security/BUCK, web/spring-security/src/main/java/uk/gov/dwp/queue/triage/web/security/spring/ldap/LdapSecurityConfig.java, web/spring-security/src/main/java/uk/gov/dwp/queue/triage/web/security/spring/ldap/LdapSecurityProperties.java, web/spring-security/src/test/java/uk/gov/dwp/queue/triage/web/security/spring/ldap/LdapSecurityPropertiesLoaderTest.java, web/spring-security/src/test/resources/spring-security-ldap-defaults.yml, web/spring-security/src/test/resources/spring-security-ldap-full.yml
Ensure that the configuration for ldap can be configured in the `application.yml` file.
Resolves #100
=> #100: Externalise LDAP configuration

core/client-test-support/BUCK, core/client-test-support/src/main/java/uk/gov/dwp/queue/triage/core/client/SearchFailedMessageResponseMatcher.java, core/client-test-support/src/main/java/uk/gov/dwp/queue/triage/core/client/SearchRequestBuilderArgumentFormatter.java, core/client/src/main/java/uk/gov/dwp/queue/triage/core/client/search/SearchFailedMessageResponse.java, core/component-test/src/main/java/uk/gov/dwp/queue/triage/core/search/SearchFailedMessageStage.java, core/component-test/src/test/java/uk/gov/dwp/queue/triage/core/delete/DeleteFailedMessageComponentTest.java, core/component-test/src/test/java/uk/gov/dwp/queue/triage/core/search/SearchFailedMessageComponentTest.java, core/dao-mongo/BUCK, core/dao-mongo/src/main/resources/mongo-queue-triage-indexes.sh, tools/rpm_build.def
Added the following build rule to `core/dao-mongo/BUCK`:
```
rpm_build(
name = 'rpm-build',
package_name = 'dwpuc-queue-triage-core-db',
rpm_prefix = 'queue-triage-core-db',
version = '1.0.0',
app_home = '/srv/app/mongo/queue-triage-core',
bin = [
'$(location :mongo-queue-triage-indexes.sh)',
'$(location :mongo-queue-triage-roles.sh)',
'$(location :mongo-queue-triage-users.sh)',
],
)
```
This creates an RPM `queue-triage-core-db-1.0.0.rpm` which contains the following files:
```
$ rpm -qilp buck-out/gen/core/dao-mongo/rpm-build/queue-triage-core-db-1.0.0.rpm 
Name        : dwpuc-queue-triage-core-db
Epoch       : 1
Version     : 1.0.0
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : default
Size        : 2307
License     : unknown
Signature   : (none) …
```
=> #115: Create Mongo indexes script and added a build rule to produce a DB RPM

.travis.yml, build.gradle
Update travis ci yml to push a release tag to the repo, when a build is triggered on master, and is not a pull request. 
Note: This has been tested against a forked master version, and the tagging occurs as expected.
=> #130: Update travis build file to perform a release tag

core/component-test/component-test.gradle, core/core-server/src/main/java/uk/gov/dwp/queue/triage/core/QueueTriageCoreApplication.java, web/component-test/src/test/java/uk/gov/dwp/queue/triage/web/component/labels/LabelManagementComponentTest.java
* Set the `maxParallelForks` and `forkEvery` property to 1 for the `:core:component-test` build
* Temporarily disabled the web `LabelManagementComponentTest`
=> Improving core component test stability

README.md
Small change to provide a link from the root `README.md` to the `core/message-classification/README.md` 
Resolves #120
=> #120: Provided a link from root README.md to the message-classification README.md

build.gradle
jcenter is currently failing resolving random dependencies:
```
Download https://jcenter.bintray.com/org/springframework/spring-beans/4.3.8.RELEASE/spring-beans-4.3.8.RELEASE.jar
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':common:metrics:compileClasspath'.
> Could not find org.springframework.boot:spring-boot-autoconfigure:1.5.3.RELEASE.
Required by:
project :common:metrics
```
=> Added mavenCentral as the first repository to query

common/health/health.gradle, common/health/src/main/java/uk/gov/dwp/queue/triage/health/PingServlet.java, core/component-test/src/main/java/uk/gov/dwp/queue/triage/core/JmsStage.java, core/component-test/src/main/java/uk/gov/dwp/queue/triage/core/classification/MessageClassificationGivenStage.java, core/component-test/src/main/java/uk/gov/dwp/queue/triage/core/stub/app/configuration/StubAppJmsConfiguration.java, core/message-classification/src/main/java/uk/gov/dwp/queue/triage/core/classification/MessageClassifier.java, core/message-classification/src/test/java/uk/gov/dwp/queue/triage/core/classification/MessageClassifierTest.java
With the creation of the `AndPredicate` and `OrPredicate` classes in commit 80de05d the MessageClassifier builder is no longer required / makes sense
=> #120: Removed unnecessary Builder from the MessageClassifier

common/health/src/main/java/uk/gov/dwp/queue/triage/health/PingServlet.java, common/id/id.gradle, common/id/src/test/java/uk/gov/dwp/queue/triage/id/FailedMessageIdTest.java, core/client/client.gradle, core/client/src/main/java/uk/gov/dwp/queue/triage/core/client/CreateFailedMessageRequest.java, core/client/src/main/java/uk/gov/dwp/queue/triage/core/client/search/SearchFailedMessageResponse.java, core/client/src/test/java/uk/gov/dwp/queue/triage/core/client/CreateFailedMessageRequestTest.java, core/client/src/test/java/uk/gov/dwp/queue/triage/core/client/search/SearchFailedMessageResponseTest.java, core/client/src/test/java/uk/gov/dwp/queue/triage/core/client/status/StatusHistoryResponseTest.java, core/core-server/src/main/java/uk/gov/dwp/queue/triage/core/configuration/FailedMessageResourceConfiguration.java, core/core-server/src/main/java/uk/gov/dwp/queue/triage/core/resource/search/FailedMessageResponseFactory.java, core/core-server/src/test/java/uk/gov/dwp/queue/triage/core/resource/search/FailedMessageResponseFactoryTest.java, core/domain/src/main/java/uk/gov/dwp/queue/triage/core/domain/FailedMessageStatusAdapter.java, core/search/search.gradle, core/search/src/main/java/uk/gov/dwp/queue/triage/core/search/SearchFailedMessageResponseAdapter.java, core/search/src/main/java/uk/gov/dwp/queue/triage/core/search/mongo/MongoSearchResponseAdapter.java, core/search/src/test/java/uk/gov/dwp/queue/triage/core/search/SearchFailedMessageResponseAdapterTest.java, web/component-test/src/test/java/uk/gov/dwp/queue/triage/web/component/delete/DeleteFailedMessageComponentTest.java, web/component-test/src/test/java/uk/gov/dwp/queue/triage/web/component/labels/LabelManagementComponentTest.java, web/component-test/src/test/java/uk/gov/dwp/queue/triage/web/component/list/ViewFailedMessagesComponentTest.java, web/component-test/src/test/java/uk/gov/dwp/queue/triage/web/component/resend/ResendFailedMessageComponentTest.java, web/component-test/src/test/java/uk/gov/dwp/queue/triage/web/component/search/SearchFailedMessageComponentTest.java, web/web-server/src/main/java/uk/gov/dwp/queue/triage/web/server/search/FailedMessageListItemAdapter.java, web/web-server/src/test/java/uk/gov/dwp/queue/triage/web/server/list/FailedMessageListItemAdapterTest.java
- Improved the test coverage further on some of the domain / client objects
- Stopped using `Optional<String>` as a type parameter for the `destination` field in the `SearchFailedMessageResponse` constructor / builder.
=> #151 - More test coverage

core/dao-mongo/dao-mongo.gradle, core/dao-mongo/src/main/java/uk/gov/dwp/queue/triage/core/dao/mongo/configuration/MongoDaoConfig.java
- Ensure the `createMongoUsers` task executes after the `createMongoRoles` task
- Resolve the issues identified by the last Sonar scan (https://sonarcloud.io/project/issues?id=queue-triage&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)
Resolves #154
=> #154 - Minor refactor

core/jms/src/main/java/uk/gov/dwp/queue/triage/core/jms/FailedMessageTransformer.java, core/jms/src/main/java/uk/gov/dwp/queue/triage/core/jms/JmsMessageDataProvider.java, core/jms/src/main/java/uk/gov/dwp/queue/triage/core/jms/JmsMessageTransformer.java, core/jms/src/main/java/uk/gov/dwp/queue/triage/core/jms/spring/FailedMessageCreator.java, core/jms/src/test/java/uk/gov/dwp/queue/triage/core/jms/FailedMessageTransformerTest.java
- Renamed `FailedMessageDataProvider` to `FailedMessageTransformer`
- Renamed `JmsMessageDataProvider` to `JmsMessageTransformer`
=> #128: Rename JmsMessageDataProvider to JmsMessageTransformer

core/vault/src/main/java/uk/gov/dwp/vault/config/VaultAutoConfiguration.java, core/vault/src/test/java/uk/gov/dwp/vault/config/QueueTriageVaultAutoConfigurationWhenVaultIsEnabledIntegrationTest.java
Adding in a Converter to transform char[] into String for *Properties objects that require passwords to be set as String. See org.springframework.boot.context.embedded.Ssl.java as an example
=> #162 - Vault resolved values which need to be bound to fields of type String.class

core/dao-mongo/dao-mongo.gradle, core/dao-mongo/src/main/java/uk/gov/dwp/queue/triage/core/dao/mongo/AuditingMongoCollection.java, core/dao-mongo/src/test/java/uk/gov/dwp/queue/triage/core/dao/mongo/AuditingMongoCollectionDelegationTest.java, core/dao-mongo/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, core/resend/src/main/java/uk/gov/dwp/queue/triage/core/resend/spring/ResendBeanDefinitionRegistryPostProcessor.java, dependency_config.gradle
- assert readOnly operations delegate to the `sourceCollection` and do not interact with the `auditCollection`
- assert log warning message for write operations that are not currently audited (these are not used by `FailedMessageDao`
=> #87: Improved test coverage of AuditMongoCollection
